// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"template-v6/server/admin-service/internal/biz"
	"template-v6/server/admin-service/internal/conf"
	"template-v6/server/admin-service/internal/data"
	"template-v6/server/admin-service/internal/server"
	"template-v6/server/admin-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	authRepo := data.NewAuthRepo(dataData)
	authUsecase := biz.NewAuthUsecase(authRepo)
	authService := service.NewAuthService(authUsecase)
	menuRepo := data.NewMenuRepo(dataData)
	menuUsecase := biz.NewMenuUsecase(menuRepo, authUsecase)
	menuService := service.NewMenuService(menuUsecase)
	roleRepo := data.NewRoleRepo(dataData)
	roleUsecase := biz.NewRoleUsecase(roleRepo, authUsecase)
	roleService := service.NewRoleService(roleUsecase)
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo, authUsecase)
	userService := service.NewUserService(userUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService, authService, menuService, roleService, userService)
	httpServer := server.NewHTTPServer(confServer, todoService, authService, menuService, roleService, userService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
