server:
  http:
    addr: 0.0.0.0:18000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/go_ant_design_pro_admin?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    network: tcp
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  object_storage:
    endpoint: ""
    region: us-east-1
    access_key: ""
    secret_key: ""
    bucket: go-ant-design-pro-admin
    force_path_style: true
    public_base_url: ""
