// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	AutoLogin     bool                   `protobuf:"varint,3,opt,name=auto_login,json=autoLogin,proto3" json:"auto_login,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetAutoLogin() bool {
	if x != nil {
		return x.AutoLogin
	}
	return false
}

func (x *LoginRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type LoginReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CurrentAuthority string                 `protobuf:"bytes,3,opt,name=current_authority,json=currentAuthority,proto3" json:"current_authority,omitempty"`
	Token            string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoginReply) GetCurrentAuthority() string {
	if x != nil {
		return x.CurrentAuthority
	}
	return ""
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *LoginReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserRequest) Reset() {
	*x = CurrentUserRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserRequest) ProtoMessage() {}

func (x *CurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUserRequest.ProtoReflect.Descriptor instead.
func (*CurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

type CurrentUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *CurrentUser           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentUserReply) Reset() {
	*x = CurrentUserReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUserReply) ProtoMessage() {}

func (x *CurrentUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUserReply.ProtoReflect.Descriptor instead.
func (*CurrentUserReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CurrentUserReply) GetData() *CurrentUser {
	if x != nil {
		return x.Data
	}
	return nil
}

type CurrentUser struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Userid            string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username          string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Avatar            string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Access            string                 `protobuf:"bytes,5,opt,name=access,proto3" json:"access,omitempty"`
	Role              string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	MenuPermissions   []string               `protobuf:"bytes,8,rep,name=menu_permissions,json=menuPermissions,proto3" json:"menu_permissions,omitempty"`
	ButtonPermissions []string               `protobuf:"bytes,9,rep,name=button_permissions,json=buttonPermissions,proto3" json:"button_permissions,omitempty"`
	RoleCodes         []string               `protobuf:"bytes,10,rep,name=role_codes,json=roleCodes,proto3" json:"role_codes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CurrentUser) Reset() {
	*x = CurrentUser{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentUser) ProtoMessage() {}

func (x *CurrentUser) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentUser.ProtoReflect.Descriptor instead.
func (*CurrentUser) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CurrentUser) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *CurrentUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CurrentUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CurrentUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CurrentUser) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *CurrentUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CurrentUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CurrentUser) GetMenuPermissions() []string {
	if x != nil {
		return x.MenuPermissions
	}
	return nil
}

func (x *CurrentUser) GetButtonPermissions() []string {
	if x != nil {
		return x.ButtonPermissions
	}
	return nil
}

func (x *CurrentUser) GetRoleCodes() []string {
	if x != nil {
		return x.RoleCodes
	}
	return nil
}

type OutLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutLoginRequest) Reset() {
	*x = OutLoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutLoginRequest) ProtoMessage() {}

func (x *OutLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutLoginRequest.ProtoReflect.Descriptor instead.
func (*OutLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

type OutLoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutLoginReply) Reset() {
	*x = OutLoginReply{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutLoginReply) ProtoMessage() {}

func (x *OutLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutLoginReply.ProtoReflect.Descriptor instead.
func (*OutLoginReply) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *OutLoginReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\fLoginRequest\x12\x1f\n" +
	"\busername\x18\x01 \x01(\tB\x03\xe0A\x02R\busername\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tB\x03\xe0A\x02R\bpassword\x12\x1d\n" +
	"\n" +
	"auto_login\x18\x03 \x01(\bR\tautoLogin\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xdb\x01\n" +
	"\n" +
	"LoginReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12+\n" +
	"\x11current_authority\x18\x03 \x01(\tR\x10currentAuthority\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12CurrentUserRequest\"<\n" +
	"\x10CurrentUserReply\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.auth.v1.CurrentUserR\x04data\"\xaa\x02\n" +
	"\vCurrentUser\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06access\x18\x05 \x01(\tR\x06access\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12)\n" +
	"\x10menu_permissions\x18\b \x03(\tR\x0fmenuPermissions\x12-\n" +
	"\x12button_permissions\x18\t \x03(\tR\x11buttonPermissions\x12\x1d\n" +
	"\n" +
	"role_codes\x18\n" +
	" \x03(\tR\troleCodes\"\x11\n" +
	"\x0fOutLoginRequest\")\n" +
	"\rOutLoginReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa0\x02\n" +
	"\vAuthService\x12R\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x13.auth.v1.LoginReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/login/account\x12_\n" +
	"\vCurrentUser\x12\x1b.auth.v1.CurrentUserRequest\x1a\x19.auth.v1.CurrentUserReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/currentUser\x12\\\n" +
	"\bOutLogin\x12\x18.auth.v1.OutLoginRequest\x1a\x16.auth.v1.OutLoginReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/login/outLoginBH\n" +
	"\aauth.v1P\x01Z/template-v6/server/admin-service/api/auth/v1;v1\xa2\x02\tAPIAuthV1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: auth.v1.LoginRequest
	(*LoginReply)(nil),            // 1: auth.v1.LoginReply
	(*CurrentUserRequest)(nil),    // 2: auth.v1.CurrentUserRequest
	(*CurrentUserReply)(nil),      // 3: auth.v1.CurrentUserReply
	(*CurrentUser)(nil),           // 4: auth.v1.CurrentUser
	(*OutLoginRequest)(nil),       // 5: auth.v1.OutLoginRequest
	(*OutLoginReply)(nil),         // 6: auth.v1.OutLoginReply
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	7, // 0: auth.v1.LoginReply.expires_at:type_name -> google.protobuf.Timestamp
	4, // 1: auth.v1.CurrentUserReply.data:type_name -> auth.v1.CurrentUser
	0, // 2: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	2, // 3: auth.v1.AuthService.CurrentUser:input_type -> auth.v1.CurrentUserRequest
	5, // 4: auth.v1.AuthService.OutLogin:input_type -> auth.v1.OutLoginRequest
	1, // 5: auth.v1.AuthService.Login:output_type -> auth.v1.LoginReply
	3, // 6: auth.v1.AuthService.CurrentUser:output_type -> auth.v1.CurrentUserReply
	6, // 7: auth.v1.AuthService.OutLogin:output_type -> auth.v1.OutLoginReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
