// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_AUTH_UNSPECIFIED         ErrorReason = 0
	ErrorReason_AUTH_INVALID_CREDENTIALS ErrorReason = 1
	ErrorReason_AUTH_DISABLED_USER       ErrorReason = 2
	ErrorReason_AUTH_MISSING_TOKEN       ErrorReason = 3
	ErrorReason_AUTH_INVALID_TOKEN       ErrorReason = 4
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "AUTH_UNSPECIFIED",
		1: "AUTH_INVALID_CREDENTIALS",
		2: "AUTH_DISABLED_USER",
		3: "AUTH_MISSING_TOKEN",
		4: "AUTH_INVALID_TOKEN",
	}
	ErrorReason_value = map[string]int32{
		"AUTH_UNSPECIFIED":         0,
		"AUTH_INVALID_CREDENTIALS": 1,
		"AUTH_DISABLED_USER":       2,
		"AUTH_MISSING_TOKEN":       3,
		"AUTH_INVALID_TOKEN":       4,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_auth_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_auth_v1_error_reason_proto protoreflect.FileDescriptor

const file_auth_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1aauth/v1/error_reason.proto\x12\aauth.v1*\x89\x01\n" +
	"\vErrorReason\x12\x14\n" +
	"\x10AUTH_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AUTH_INVALID_CREDENTIALS\x10\x01\x12\x16\n" +
	"\x12AUTH_DISABLED_USER\x10\x02\x12\x16\n" +
	"\x12AUTH_MISSING_TOKEN\x10\x03\x12\x16\n" +
	"\x12AUTH_INVALID_TOKEN\x10\x04BH\n" +
	"\aauth.v1P\x01Z/template-v6/server/admin-service/api/auth/v1;v1\xa2\x02\tAPIAuthV1b\x06proto3"

var (
	file_auth_v1_error_reason_proto_rawDescOnce sync.Once
	file_auth_v1_error_reason_proto_rawDescData []byte
)

func file_auth_v1_error_reason_proto_rawDescGZIP() []byte {
	file_auth_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_auth_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_error_reason_proto_rawDesc), len(file_auth_v1_error_reason_proto_rawDesc)))
	})
	return file_auth_v1_error_reason_proto_rawDescData
}

var file_auth_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: auth.v1.ErrorReason
}
var file_auth_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_error_reason_proto_init() }
func file_auth_v1_error_reason_proto_init() {
	if File_auth_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_error_reason_proto_rawDesc), len(file_auth_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_auth_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_auth_v1_error_reason_proto_enumTypes,
	}.Build()
	File_auth_v1_error_reason_proto = out.File
	file_auth_v1_error_reason_proto_goTypes = nil
	file_auth_v1_error_reason_proto_depIdxs = nil
}
