apiVersion: 1

datasources:
  - name: Higress Prometheus
    type: prometheus
    uid: higress-prometheus
    access: proxy
    url: http://template-v6-prometheus:9090
    isDefault: true
    editable: true

