// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_SYSTEM_UNSPECIFIED             ErrorReason = 0
	ErrorReason_SYSTEM_UNAUTHORIZED            ErrorReason = 1
	ErrorReason_MENU_NOT_FOUND                 ErrorReason = 2
	ErrorReason_MENU_DUPLICATE_PERMISSION_CODE ErrorReason = 3
	ErrorReason_MENU_INVALID_PARENT            ErrorReason = 4
	ErrorReason_MENU_HAS_CHILDREN              ErrorReason = 5
	ErrorReason_MENU_HAS_ROLE_BINDINGS         ErrorReason = 6
	ErrorReason_MENU_INVALID_TYPE              ErrorReason = 7
	ErrorReason_ROLE_NOT_FOUND                 ErrorReason = 8
	ErrorReason_ROLE_DUPLICATE_CODE            ErrorReason = 9
	ErrorReason_ROLE_HAS_USERS                 ErrorReason = 10
	ErrorReason_ROLE_INVALID_ARGUMENT          ErrorReason = 11
	ErrorReason_USER_NOT_FOUND                 ErrorReason = 12
	ErrorReason_USER_DUPLICATE_USERNAME        ErrorReason = 13
	ErrorReason_USER_INVALID_ARGUMENT          ErrorReason = 14
	ErrorReason_USER_CANNOT_DELETE_SELF        ErrorReason = 15
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "SYSTEM_UNSPECIFIED",
		1:  "SYSTEM_UNAUTHORIZED",
		2:  "MENU_NOT_FOUND",
		3:  "MENU_DUPLICATE_PERMISSION_CODE",
		4:  "MENU_INVALID_PARENT",
		5:  "MENU_HAS_CHILDREN",
		6:  "MENU_HAS_ROLE_BINDINGS",
		7:  "MENU_INVALID_TYPE",
		8:  "ROLE_NOT_FOUND",
		9:  "ROLE_DUPLICATE_CODE",
		10: "ROLE_HAS_USERS",
		11: "ROLE_INVALID_ARGUMENT",
		12: "USER_NOT_FOUND",
		13: "USER_DUPLICATE_USERNAME",
		14: "USER_INVALID_ARGUMENT",
		15: "USER_CANNOT_DELETE_SELF",
	}
	ErrorReason_value = map[string]int32{
		"SYSTEM_UNSPECIFIED":             0,
		"SYSTEM_UNAUTHORIZED":            1,
		"MENU_NOT_FOUND":                 2,
		"MENU_DUPLICATE_PERMISSION_CODE": 3,
		"MENU_INVALID_PARENT":            4,
		"MENU_HAS_CHILDREN":              5,
		"MENU_HAS_ROLE_BINDINGS":         6,
		"MENU_INVALID_TYPE":              7,
		"ROLE_NOT_FOUND":                 8,
		"ROLE_DUPLICATE_CODE":            9,
		"ROLE_HAS_USERS":                 10,
		"ROLE_INVALID_ARGUMENT":          11,
		"USER_NOT_FOUND":                 12,
		"USER_DUPLICATE_USERNAME":        13,
		"USER_INVALID_ARGUMENT":          14,
		"USER_CANNOT_DELETE_SELF":        15,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_system_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_system_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_system_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_system_v1_error_reason_proto protoreflect.FileDescriptor

const file_system_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1csystem/v1/error_reason.proto\x12\tsystem.v1*\x9e\x03\n" +
	"\vErrorReason\x12\x16\n" +
	"\x12SYSTEM_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SYSTEM_UNAUTHORIZED\x10\x01\x12\x12\n" +
	"\x0eMENU_NOT_FOUND\x10\x02\x12\"\n" +
	"\x1eMENU_DUPLICATE_PERMISSION_CODE\x10\x03\x12\x17\n" +
	"\x13MENU_INVALID_PARENT\x10\x04\x12\x15\n" +
	"\x11MENU_HAS_CHILDREN\x10\x05\x12\x1a\n" +
	"\x16MENU_HAS_ROLE_BINDINGS\x10\x06\x12\x15\n" +
	"\x11MENU_INVALID_TYPE\x10\a\x12\x12\n" +
	"\x0eROLE_NOT_FOUND\x10\b\x12\x17\n" +
	"\x13ROLE_DUPLICATE_CODE\x10\t\x12\x12\n" +
	"\x0eROLE_HAS_USERS\x10\n" +
	"\x12\x19\n" +
	"\x15ROLE_INVALID_ARGUMENT\x10\v\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\f\x12\x1b\n" +
	"\x17USER_DUPLICATE_USERNAME\x10\r\x12\x19\n" +
	"\x15USER_INVALID_ARGUMENT\x10\x0e\x12\x1b\n" +
	"\x17USER_CANNOT_DELETE_SELF\x10\x0fBN\n" +
	"\tsystem.v1P\x01Z1template-v6/server/admin-service/api/system/v1;v1\xa2\x02\vAPISystemV1b\x06proto3"

var (
	file_system_v1_error_reason_proto_rawDescOnce sync.Once
	file_system_v1_error_reason_proto_rawDescData []byte
)

func file_system_v1_error_reason_proto_rawDescGZIP() []byte {
	file_system_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_system_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_error_reason_proto_rawDesc), len(file_system_v1_error_reason_proto_rawDesc)))
	})
	return file_system_v1_error_reason_proto_rawDescData
}

var file_system_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_system_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: system.v1.ErrorReason
}
var file_system_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_system_v1_error_reason_proto_init() }
func file_system_v1_error_reason_proto_init() {
	if File_system_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_error_reason_proto_rawDesc), len(file_system_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_system_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_system_v1_error_reason_proto_enumTypes,
	}.Build()
	File_system_v1_error_reason_proto = out.File
	file_system_v1_error_reason_proto_goTypes = nil
	file_system_v1_error_reason_proto_depIdxs = nil
}
