// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/v1/module.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Hidden        bool                   `protobuf:"varint,9,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_system_v1_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Module) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Module) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Module) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Module) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Module) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type ListModulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesRequest) Reset() {
	*x = ListModulesRequest{}
	mi := &file_system_v1_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesRequest) ProtoMessage() {}

func (x *ListModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesRequest.ProtoReflect.Descriptor instead.
func (*ListModulesRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{1}
}

type ListModulesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Module              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModulesReply) Reset() {
	*x = ListModulesReply{}
	mi := &file_system_v1_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModulesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModulesReply) ProtoMessage() {}

func (x *ListModulesReply) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModulesReply.ProtoReflect.Descriptor instead.
func (*ListModulesReply) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{2}
}

func (x *ListModulesReply) GetData() []*Module {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleRequest) Reset() {
	*x = GetModuleRequest{}
	mi := &file_system_v1_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleRequest) ProtoMessage() {}

func (x *GetModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleRequest.ProtoReflect.Descriptor instead.
func (*GetModuleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{3}
}

func (x *GetModuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Hidden        bool                   `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModuleRequest) Reset() {
	*x = CreateModuleRequest{}
	mi := &file_system_v1_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModuleRequest) ProtoMessage() {}

func (x *CreateModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModuleRequest.ProtoReflect.Descriptor instead.
func (*CreateModuleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{4}
}

func (x *CreateModuleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModuleRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateModuleRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateModuleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateModuleRequest) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type UpdateModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Hidden        bool                   `protobuf:"varint,7,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModuleRequest) Reset() {
	*x = UpdateModuleRequest{}
	mi := &file_system_v1_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModuleRequest) ProtoMessage() {}

func (x *UpdateModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateModuleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateModuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModuleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateModuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateModuleRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateModuleRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateModuleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateModuleRequest) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type DeleteModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModuleRequest) Reset() {
	*x = DeleteModuleRequest{}
	mi := &file_system_v1_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModuleRequest) ProtoMessage() {}

func (x *DeleteModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteModuleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteModuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MigrateModuleMenusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetModuleId string                 `protobuf:"bytes,2,opt,name=target_module_id,json=targetModuleId,proto3" json:"target_module_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MigrateModuleMenusRequest) Reset() {
	*x = MigrateModuleMenusRequest{}
	mi := &file_system_v1_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateModuleMenusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateModuleMenusRequest) ProtoMessage() {}

func (x *MigrateModuleMenusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateModuleMenusRequest.ProtoReflect.Descriptor instead.
func (*MigrateModuleMenusRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{7}
}

func (x *MigrateModuleMenusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MigrateModuleMenusRequest) GetTargetModuleId() string {
	if x != nil {
		return x.TargetModuleId
	}
	return ""
}

type MigrateModuleMenusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateModuleMenusReply) Reset() {
	*x = MigrateModuleMenusReply{}
	mi := &file_system_v1_module_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateModuleMenusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateModuleMenusReply) ProtoMessage() {}

func (x *MigrateModuleMenusReply) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_module_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateModuleMenusReply.ProtoReflect.Descriptor instead.
func (*MigrateModuleMenusReply) Descriptor() ([]byte, []int) {
	return file_system_v1_module_proto_rawDescGZIP(), []int{8}
}

func (x *MigrateModuleMenusReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_system_v1_module_proto protoreflect.FileDescriptor

const file_system_v1_module_proto_rawDesc = "" +
	"\n" +
	"\x16system/v1/module.proto\x12\tsystem.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06hidden\x18\t \x01(\bR\x06hidden\"\x14\n" +
	"\x12ListModulesRequest\"9\n" +
	"\x10ListModulesReply\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.system.v1.ModuleR\x04data\"'\n" +
	"\x10GetModuleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x9f\x01\n" +
	"\x13CreateModuleRequest\x12\x17\n" +
	"\x04code\x18\x01 \x01(\tB\x03\xe0A\x02R\x04code\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06hidden\x18\x06 \x01(\bR\x06hidden\"\xb4\x01\n" +
	"\x13UpdateModuleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tB\x03\xe0A\x02R\x04code\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tB\x03\xe0A\x02R\x04name\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06hidden\x18\a \x01(\bR\x06hidden\"*\n" +
	"\x13DeleteModuleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"_\n" +
	"\x19MigrateModuleMenusRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12-\n" +
	"\x10target_module_id\x18\x02 \x01(\tB\x03\xe0A\x02R\x0etargetModuleId\"3\n" +
	"\x17MigrateModuleMenusReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9f\x05\n" +
	"\rModuleService\x12f\n" +
	"\vListModules\x12\x1d.system.v1.ListModulesRequest\x1a\x1b.system.v1.ListModulesReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/system/modules\x12]\n" +
	"\tGetModule\x12\x1b.system.v1.GetModuleRequest\x1a\x11.system.v1.Module\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/system/modules/{id}\x12a\n" +
	"\fCreateModule\x12\x1e.system.v1.CreateModuleRequest\x1a\x11.system.v1.Module\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/system/modules\x12f\n" +
	"\fUpdateModule\x12\x1e.system.v1.UpdateModuleRequest\x1a\x11.system.v1.Module\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/system/modules/{id}\x12h\n" +
	"\fDeleteModule\x12\x1e.system.v1.DeleteModuleRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/system/modules/{id}\x12\x91\x01\n" +
	"\x12MigrateModuleMenus\x12$.system.v1.MigrateModuleMenusRequest\x1a\".system.v1.MigrateModuleMenusReply\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/system/modules/{id}/migrate-menusBN\n" +
	"\tsystem.v1P\x01Z1template-v6/server/admin-service/api/system/v1;v1\xa2\x02\vAPISystemV1b\x06proto3"

var (
	file_system_v1_module_proto_rawDescOnce sync.Once
	file_system_v1_module_proto_rawDescData []byte
)

func file_system_v1_module_proto_rawDescGZIP() []byte {
	file_system_v1_module_proto_rawDescOnce.Do(func() {
		file_system_v1_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_module_proto_rawDesc), len(file_system_v1_module_proto_rawDesc)))
	})
	return file_system_v1_module_proto_rawDescData
}

var file_system_v1_module_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_system_v1_module_proto_goTypes = []any{
	(*Module)(nil),                    // 0: system.v1.Module
	(*ListModulesRequest)(nil),        // 1: system.v1.ListModulesRequest
	(*ListModulesReply)(nil),          // 2: system.v1.ListModulesReply
	(*GetModuleRequest)(nil),          // 3: system.v1.GetModuleRequest
	(*CreateModuleRequest)(nil),       // 4: system.v1.CreateModuleRequest
	(*UpdateModuleRequest)(nil),       // 5: system.v1.UpdateModuleRequest
	(*DeleteModuleRequest)(nil),       // 6: system.v1.DeleteModuleRequest
	(*MigrateModuleMenusRequest)(nil), // 7: system.v1.MigrateModuleMenusRequest
	(*MigrateModuleMenusReply)(nil),   // 8: system.v1.MigrateModuleMenusReply
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_system_v1_module_proto_depIdxs = []int32{
	9,  // 0: system.v1.Module.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: system.v1.Module.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: system.v1.ListModulesReply.data:type_name -> system.v1.Module
	1,  // 3: system.v1.ModuleService.ListModules:input_type -> system.v1.ListModulesRequest
	3,  // 4: system.v1.ModuleService.GetModule:input_type -> system.v1.GetModuleRequest
	4,  // 5: system.v1.ModuleService.CreateModule:input_type -> system.v1.CreateModuleRequest
	5,  // 6: system.v1.ModuleService.UpdateModule:input_type -> system.v1.UpdateModuleRequest
	6,  // 7: system.v1.ModuleService.DeleteModule:input_type -> system.v1.DeleteModuleRequest
	7,  // 8: system.v1.ModuleService.MigrateModuleMenus:input_type -> system.v1.MigrateModuleMenusRequest
	2,  // 9: system.v1.ModuleService.ListModules:output_type -> system.v1.ListModulesReply
	0,  // 10: system.v1.ModuleService.GetModule:output_type -> system.v1.Module
	0,  // 11: system.v1.ModuleService.CreateModule:output_type -> system.v1.Module
	0,  // 12: system.v1.ModuleService.UpdateModule:output_type -> system.v1.Module
	10, // 13: system.v1.ModuleService.DeleteModule:output_type -> google.protobuf.Empty
	8,  // 14: system.v1.ModuleService.MigrateModuleMenus:output_type -> system.v1.MigrateModuleMenusReply
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_system_v1_module_proto_init() }
func file_system_v1_module_proto_init() {
	if File_system_v1_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_module_proto_rawDesc), len(file_system_v1_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_module_proto_goTypes,
		DependencyIndexes: file_system_v1_module_proto_depIdxs,
		MessageInfos:      file_system_v1_module_proto_msgTypes,
	}.Build()
	File_system_v1_module_proto = out.File
	file_system_v1_module_proto_goTypes = nil
	file_system_v1_module_proto_depIdxs = nil
}
