// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: system/v1/module.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationModuleServiceCreateModule = "/system.v1.ModuleService/CreateModule"
const OperationModuleServiceDeleteModule = "/system.v1.ModuleService/DeleteModule"
const OperationModuleServiceGetModule = "/system.v1.ModuleService/GetModule"
const OperationModuleServiceListModules = "/system.v1.ModuleService/ListModules"
const OperationModuleServiceMigrateModuleMenus = "/system.v1.ModuleService/MigrateModuleMenus"
const OperationModuleServiceUpdateModule = "/system.v1.ModuleService/UpdateModule"

type ModuleServiceHTTPServer interface {
	CreateModule(context.Context, *CreateModuleRequest) (*Module, error)
	DeleteModule(context.Context, *DeleteModuleRequest) (*emptypb.Empty, error)
	GetModule(context.Context, *GetModuleRequest) (*Module, error)
	ListModules(context.Context, *ListModulesRequest) (*ListModulesReply, error)
	MigrateModuleMenus(context.Context, *MigrateModuleMenusRequest) (*MigrateModuleMenusReply, error)
	UpdateModule(context.Context, *UpdateModuleRequest) (*Module, error)
}

func RegisterModuleServiceHTTPServer(s *http.Server, srv ModuleServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/system/modules", _ModuleService_ListModules0_HTTP_Handler(srv))
	r.Handle("GET", "/api/system/modules/{id}", _ModuleService_GetModule0_HTTP_Handler(srv))
	r.Handle("POST", "/api/system/modules", _ModuleService_CreateModule0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/system/modules/{id}", _ModuleService_UpdateModule0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/system/modules/{id}", _ModuleService_DeleteModule0_HTTP_Handler(srv))
	r.Handle("POST", "/api/system/modules/{id}/migrate-menus", _ModuleService_MigrateModuleMenus0_HTTP_Handler(srv))
}

func _ModuleService_ListModules0_HTTP_Handler(srv ModuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListModulesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModuleServiceListModules)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListModules(ctx, req.(*ListModulesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListModulesReply)
		return ctx.Result(200, reply)
	}
}

func _ModuleService_GetModule0_HTTP_Handler(srv ModuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetModuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModuleServiceGetModule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetModule(ctx, req.(*GetModuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Module)
		return ctx.Result(200, reply)
	}
}

func _ModuleService_CreateModule0_HTTP_Handler(srv ModuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateModuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModuleServiceCreateModule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateModule(ctx, req.(*CreateModuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Module)
		return ctx.Result(200, reply)
	}
}

func _ModuleService_UpdateModule0_HTTP_Handler(srv ModuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateModuleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModuleServiceUpdateModule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateModule(ctx, req.(*UpdateModuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Module)
		return ctx.Result(200, reply)
	}
}

func _ModuleService_DeleteModule0_HTTP_Handler(srv ModuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteModuleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModuleServiceDeleteModule)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteModule(ctx, req.(*DeleteModuleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ModuleService_MigrateModuleMenus0_HTTP_Handler(srv ModuleServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MigrateModuleMenusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationModuleServiceMigrateModuleMenus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MigrateModuleMenus(ctx, req.(*MigrateModuleMenusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MigrateModuleMenusReply)
		return ctx.Result(200, reply)
	}
}

type ModuleServiceHTTPClient interface {
	CreateModule(ctx context.Context, req *CreateModuleRequest, opts ...http.CallOption) (rsp *Module, err error)
	DeleteModule(ctx context.Context, req *DeleteModuleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetModule(ctx context.Context, req *GetModuleRequest, opts ...http.CallOption) (rsp *Module, err error)
	ListModules(ctx context.Context, req *ListModulesRequest, opts ...http.CallOption) (rsp *ListModulesReply, err error)
	MigrateModuleMenus(ctx context.Context, req *MigrateModuleMenusRequest, opts ...http.CallOption) (rsp *MigrateModuleMenusReply, err error)
	UpdateModule(ctx context.Context, req *UpdateModuleRequest, opts ...http.CallOption) (rsp *Module, err error)
}

type ModuleServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewModuleServiceHTTPClient(client *http.Client) ModuleServiceHTTPClient {
	return &ModuleServiceHTTPClientImpl{client}
}

func (c *ModuleServiceHTTPClientImpl) CreateModule(ctx context.Context, in *CreateModuleRequest, opts ...http.CallOption) (*Module, error) {
	var out Module
	pattern := "/api/system/modules"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationModuleServiceCreateModule),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModuleServiceHTTPClientImpl) DeleteModule(ctx context.Context, in *DeleteModuleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/system/modules/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationModuleServiceDeleteModule),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModuleServiceHTTPClientImpl) GetModule(ctx context.Context, in *GetModuleRequest, opts ...http.CallOption) (*Module, error) {
	var out Module
	pattern := "/api/system/modules/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationModuleServiceGetModule),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModuleServiceHTTPClientImpl) ListModules(ctx context.Context, in *ListModulesRequest, opts ...http.CallOption) (*ListModulesReply, error) {
	var out ListModulesReply
	pattern := "/api/system/modules"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationModuleServiceListModules),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModuleServiceHTTPClientImpl) MigrateModuleMenus(ctx context.Context, in *MigrateModuleMenusRequest, opts ...http.CallOption) (*MigrateModuleMenusReply, error) {
	var out MigrateModuleMenusReply
	pattern := "/api/system/modules/{id}/migrate-menus"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationModuleServiceMigrateModuleMenus),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ModuleServiceHTTPClientImpl) UpdateModule(ctx context.Context, in *UpdateModuleRequest, opts ...http.CallOption) (*Module, error) {
	var out Module
	pattern := "/api/system/modules/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationModuleServiceUpdateModule),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
