// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: system/v1/role.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PermissionIds []string               `protobuf:"bytes,6,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_system_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_system_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Role) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

func (x *Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_system_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_role_proto_rawDescGZIP(), []int{1}
}

type ListRolesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Role                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesReply) Reset() {
	*x = ListRolesReply{}
	mi := &file_system_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesReply) ProtoMessage() {}

func (x *ListRolesReply) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesReply.ProtoReflect.Descriptor instead.
func (*ListRolesReply) Descriptor() ([]byte, []int) {
	return file_system_v1_role_proto_rawDescGZIP(), []int{2}
}

func (x *ListRolesReply) GetData() []*Role {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_system_v1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_role_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_system_v1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_role_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_system_v1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_role_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_system_v1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_role_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateRolePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PermissionIds []string               `protobuf:"bytes,2,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRolePermissionsRequest) Reset() {
	*x = UpdateRolePermissionsRequest{}
	mi := &file_system_v1_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRolePermissionsRequest) ProtoMessage() {}

func (x *UpdateRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_role_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRolePermissionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRolePermissionsRequest) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

var File_system_v1_role_proto protoreflect.FileDescriptor

const file_system_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x14system/v1/role.proto\x12\tsystem.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x02\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0epermission_ids\x18\x06 \x03(\tR\rpermissionIds\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x12\n" +
	"\x10ListRolesRequest\"5\n" +
	"\x0eListRolesReply\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.system.v1.RoleR\x04data\"%\n" +
	"\x0eGetRoleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\x7f\n" +
	"\x11CreateRoleRequest\x12\x17\n" +
	"\x04code\x18\x01 \x01(\tB\x03\xe0A\x02R\x04code\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x94\x01\n" +
	"\x11UpdateRoleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04code\x18\x02 \x01(\tB\x03\xe0A\x02R\x04code\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tB\x03\xe0A\x02R\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"(\n" +
	"\x11DeleteRoleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"Z\n" +
	"\x1cUpdateRolePermissionsRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\tR\rpermissionIds2\xe6\x04\n" +
	"\vRoleService\x12^\n" +
	"\tListRoles\x12\x1b.system.v1.ListRolesRequest\x1a\x19.system.v1.ListRolesReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/system/roles\x12U\n" +
	"\aGetRole\x12\x19.system.v1.GetRoleRequest\x1a\x0f.system.v1.Role\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/system/roles/{id}\x12Y\n" +
	"\n" +
	"CreateRole\x12\x1c.system.v1.CreateRoleRequest\x1a\x0f.system.v1.Role\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/system/roles\x12^\n" +
	"\n" +
	"UpdateRole\x12\x1c.system.v1.UpdateRoleRequest\x1a\x0f.system.v1.Role\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/system/roles/{id}\x12b\n" +
	"\n" +
	"DeleteRole\x12\x1c.system.v1.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/system/roles/{id}\x12\x80\x01\n" +
	"\x15UpdateRolePermissions\x12'.system.v1.UpdateRolePermissionsRequest\x1a\x0f.system.v1.Role\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/api/system/roles/{id}/permissionsBN\n" +
	"\tsystem.v1P\x01Z1template-v6/server/admin-service/api/system/v1;v1\xa2\x02\vAPISystemV1b\x06proto3"

var (
	file_system_v1_role_proto_rawDescOnce sync.Once
	file_system_v1_role_proto_rawDescData []byte
)

func file_system_v1_role_proto_rawDescGZIP() []byte {
	file_system_v1_role_proto_rawDescOnce.Do(func() {
		file_system_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_role_proto_rawDesc), len(file_system_v1_role_proto_rawDesc)))
	})
	return file_system_v1_role_proto_rawDescData
}

var file_system_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_system_v1_role_proto_goTypes = []any{
	(*Role)(nil),                         // 0: system.v1.Role
	(*ListRolesRequest)(nil),             // 1: system.v1.ListRolesRequest
	(*ListRolesReply)(nil),               // 2: system.v1.ListRolesReply
	(*GetRoleRequest)(nil),               // 3: system.v1.GetRoleRequest
	(*CreateRoleRequest)(nil),            // 4: system.v1.CreateRoleRequest
	(*UpdateRoleRequest)(nil),            // 5: system.v1.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),            // 6: system.v1.DeleteRoleRequest
	(*UpdateRolePermissionsRequest)(nil), // 7: system.v1.UpdateRolePermissionsRequest
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 9: google.protobuf.Empty
}
var file_system_v1_role_proto_depIdxs = []int32{
	8, // 0: system.v1.Role.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: system.v1.Role.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: system.v1.ListRolesReply.data:type_name -> system.v1.Role
	1, // 3: system.v1.RoleService.ListRoles:input_type -> system.v1.ListRolesRequest
	3, // 4: system.v1.RoleService.GetRole:input_type -> system.v1.GetRoleRequest
	4, // 5: system.v1.RoleService.CreateRole:input_type -> system.v1.CreateRoleRequest
	5, // 6: system.v1.RoleService.UpdateRole:input_type -> system.v1.UpdateRoleRequest
	6, // 7: system.v1.RoleService.DeleteRole:input_type -> system.v1.DeleteRoleRequest
	7, // 8: system.v1.RoleService.UpdateRolePermissions:input_type -> system.v1.UpdateRolePermissionsRequest
	2, // 9: system.v1.RoleService.ListRoles:output_type -> system.v1.ListRolesReply
	0, // 10: system.v1.RoleService.GetRole:output_type -> system.v1.Role
	0, // 11: system.v1.RoleService.CreateRole:output_type -> system.v1.Role
	0, // 12: system.v1.RoleService.UpdateRole:output_type -> system.v1.Role
	9, // 13: system.v1.RoleService.DeleteRole:output_type -> google.protobuf.Empty
	0, // 14: system.v1.RoleService.UpdateRolePermissions:output_type -> system.v1.Role
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_system_v1_role_proto_init() }
func file_system_v1_role_proto_init() {
	if File_system_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_role_proto_rawDesc), len(file_system_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_role_proto_goTypes,
		DependencyIndexes: file_system_v1_role_proto_depIdxs,
		MessageInfos:      file_system_v1_role_proto_msgTypes,
	}.Build()
	File_system_v1_role_proto = out.File
	file_system_v1_role_proto_goTypes = nil
	file_system_v1_role_proto_depIdxs = nil
}
