// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: profile/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_PROFILE_UNSPECIFIED         ErrorReason = 0
	ErrorReason_PROFILE_INVALID_ARGUMENT    ErrorReason = 1
	ErrorReason_PROFILE_INVALID_PASSWORD    ErrorReason = 2
	ErrorReason_PROFILE_STORAGE_UNAVAILABLE ErrorReason = 3
	ErrorReason_PROFILE_SAVE_FAILED         ErrorReason = 4
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "PROFILE_UNSPECIFIED",
		1: "PROFILE_INVALID_ARGUMENT",
		2: "PROFILE_INVALID_PASSWORD",
		3: "PROFILE_STORAGE_UNAVAILABLE",
		4: "PROFILE_SAVE_FAILED",
	}
	ErrorReason_value = map[string]int32{
		"PROFILE_UNSPECIFIED":         0,
		"PROFILE_INVALID_ARGUMENT":    1,
		"PROFILE_INVALID_PASSWORD":    2,
		"PROFILE_STORAGE_UNAVAILABLE": 3,
		"PROFILE_SAVE_FAILED":         4,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_profile_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_profile_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_profile_v1_error_reason_proto protoreflect.FileDescriptor

const file_profile_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1dprofile/v1/error_reason.proto\x12\n" +
	"profile.v1*\x9c\x01\n" +
	"\vErrorReason\x12\x17\n" +
	"\x13PROFILE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PROFILE_INVALID_ARGUMENT\x10\x01\x12\x1c\n" +
	"\x18PROFILE_INVALID_PASSWORD\x10\x02\x12\x1f\n" +
	"\x1bPROFILE_STORAGE_UNAVAILABLE\x10\x03\x12\x17\n" +
	"\x13PROFILE_SAVE_FAILED\x10\x04BQ\n" +
	"\n" +
	"profile.v1P\x01Z2template-v6/server/admin-service/api/profile/v1;v1\xa2\x02\fAPIProfileV1b\x06proto3"

var (
	file_profile_v1_error_reason_proto_rawDescOnce sync.Once
	file_profile_v1_error_reason_proto_rawDescData []byte
)

func file_profile_v1_error_reason_proto_rawDescGZIP() []byte {
	file_profile_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_profile_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_error_reason_proto_rawDesc), len(file_profile_v1_error_reason_proto_rawDesc)))
	})
	return file_profile_v1_error_reason_proto_rawDescData
}

var file_profile_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profile_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: profile.v1.ErrorReason
}
var file_profile_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profile_v1_error_reason_proto_init() }
func file_profile_v1_error_reason_proto_init() {
	if File_profile_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_error_reason_proto_rawDesc), len(file_profile_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_profile_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_profile_v1_error_reason_proto_enumTypes,
	}.Build()
	File_profile_v1_error_reason_proto = out.File
	file_profile_v1_error_reason_proto_goTypes = nil
	file_profile_v1_error_reason_proto_depIdxs = nil
}
