// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: profile/v1/profile.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationProfileServiceChangePassword = "/profile.v1.ProfileService/ChangePassword"
const OperationProfileServiceGetProfile = "/profile.v1.ProfileService/GetProfile"
const OperationProfileServiceUpdateProfile = "/profile.v1.ProfileService/UpdateProfile"

type ProfileServiceHTTPServer interface {
	ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileReply, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*GetProfileReply, error)
}

func RegisterProfileServiceHTTPServer(s *http.Server, srv ProfileServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/profile", _ProfileService_GetProfile0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/profile", _ProfileService_UpdateProfile0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/profile/password", _ProfileService_ChangePassword0_HTTP_Handler(srv))
}

func _ProfileService_GetProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProfileReply)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_UpdateProfile0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProfileReply)
		return ctx.Result(200, reply)
	}
}

func _ProfileService_ChangePassword0_HTTP_Handler(srv ProfileServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangePasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProfileServiceChangePassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangePassword(ctx, req.(*ChangePasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type ProfileServiceHTTPClient interface {
	ChangePassword(ctx context.Context, req *ChangePasswordRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *GetProfileReply, err error)
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...http.CallOption) (rsp *GetProfileReply, err error)
}

type ProfileServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProfileServiceHTTPClient(client *http.Client) ProfileServiceHTTPClient {
	return &ProfileServiceHTTPClientImpl{client}
}

func (c *ProfileServiceHTTPClientImpl) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/profile/password"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProfileServiceChangePassword),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*GetProfileReply, error) {
	var out GetProfileReply
	pattern := "/api/profile"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProfileServiceGetProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProfileServiceHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...http.CallOption) (*GetProfileReply, error) {
	var out GetProfileReply
	pattern := "/api/profile"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProfileServiceUpdateProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
